version: '3.7'
services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    volumes:
      - ./app:/app
      # exclude data volumes
      # - /app/src/node_modules
    tty: true
    stdin_open: true
    # Hot Module Replacement (HMR) is enable for virtual box.
    environment:
      - CHOKIDAR_USEPOLLING=true